[[annotation]]
file="/wehisan/bioinf/Bioinformatics/databases/bahlolab_db/ExAC_release/release0.3/ExAC.r0.3.sites.vep.vcf.gz"
fields = ["AC_Adj", "AC_Hom", "AC_Hemiz", "AN_Adj", "FILTER"]
ops=["self", "self", "self", "self", "self"]
names=["ExAC_AC", "ExAC_Hom", "ExAC_Hemiz", "ExAC_AN", "ExAC_FILTER"]

[[annotation]]
file="/wehisan/bioinf/Bioinformatics/databases/bahlolab_db/gnomAD_data/release-170228/vcf/exomes/gnomad.exomes.r2.0.1.sites.vcf.gz"
fields = ["AC", "Hom", "Hemiz", "AN", "FILTER"]
ops=["self", "self", "self", "self", "self"]
names=["gnomAD_exome_AC", "gnomAD_exome_Hom", "gnomAD_exome_Hemiz", "gnomAD_exome_AN", "gnomAD_exome_FILTER"]


# Calculate allele frequencies
[[postannotation]]
fields=["ExAC_AC", "ExAC_AN"]
name="ExAC_AF"
op="div2"
type="Float"

[[postannotation]]
fields=["gnomAD_exome_AC", "gnomAD_exome_AN"]
name="gnomAD_exome_AF"
op="div2"
type="Float"

